name: sehatku
description: Sehatku App
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
  fonts:
    - family: Gilroy
      fonts:
        - asset: lib/assets/fonts/gilroy/Gilroy-Light.otf
        - asset: lib/assets/fonts/gilroy/Gilroy-ExtraBold.otf

    - family: Proxima Nova
      fonts:
        - asset: lib/assets/fonts/proxima_nova/ProximaNova-Regular.otf
          weight: 400
        - asset: lib/assets/fonts/proxima_nova/ProximaNova-Semibold.otf
          weight: 500
        - asset: lib/assets/fonts/proxima_nova/ProximaNova-Bold.otf
          weight: 600
